export const data = {
    author:{
        name: "Neil Gaiman",
        authorImg: "https://images2.imgbox.com/e2/32/uFpMJtBN_o.png",
        stars: 5,
        description: "Neil Richard MacKinnon Gaiman, nascido em Portchester no dia 10 de novembro de 1960 é um autor britânico de contos, romances, banda desenhada e roteiros radicado nos Estados Unidos.",
        books: [
            {
                id: 1,
                slug: "neve-vidro-macas",
                title: "Neve, vidro e maçãs",
                category: "Conto / Ficção",
                year: 2019,
                rate: 4.8,
                avaliations:1253,
                shortDescription:"Em 'Neve, vidro e maçãs' Gaiman fez uma original adaptação de Branca de Neve, e o estilo literário do autor está impecável.",
                description: "Em 'Neve, vidro e maçãs' Gaiman fez uma original adaptação de Branca de Neve, e o estilo literário do autor está impecável. A narrativa trás outra versão da história, dessa vez contada pela madrastra da princesinha órfã.<br>Numa assustadora subversão do conto da Branca de Neve, descobrimos, a partir do ponto de vista da madrasta, como a princesa da pele da cor de neve era na verdade uma peculiar e terrível criatura. Alimentando-se do sangue de seu pai, da madrasta e do príncipe, a Branca de Neve desta história causa terror no reino, e apenas a sabedoria da madrasta poderia impedi-la. Ao adicionar toques sinistros ao famoso conto de fadas, Neil Gaiman cria uma história realmente apavorante.",
                bookCover: "https://images2.imgbox.com/b7/1d/cNTPdQsG_o.png"

            },
            {
                id: 2,
                slug: "mitologia-nordica",
                title: "Mitologia nórdica",
                category: "Mito / Literatura fantástica",
                year: 2017,
                rate: 4.1,
                avaliations:998,
                shortDescription: "Fascinado por essa mitologia desde a infância, o autor compôs uma coletânea de quinze contos que começa com a narração da origem do mundo e mostra a relação conturbada entre deuses.",
                description: "Fascinado por essa mitologia desde a infância, o autor compôs uma coletânea de quinze contos que começa com a narração da origem do mundo e mostra a relação conturbada entre deuses, gigantes e anões, indo até o Ragnarök, o assustador cenário do apocalipse que vai levar ao fim no mundo. <br> Às vezes intensos e sombrios, outras vezes divertidos e heroicos, os contos retratam tempos longínquos em que os feitos dos deuses eram contados ao redor da fogueira em noites frias e estreladas. Mitologia nórdica é o livro perfeito para quem quer descobrir mais sobre a mitologia escandinava e também para aqueles que desejam desvelar novas facetas dessas histórias.",
                bookCover: "https://images2.imgbox.com/72/8e/tsBVPjvK_o.png",
            },
            {
                id: 3,
                slug: "criaturas-estranhas",
                title: "Criaturas estranhas",
                category: "Literatura fantástica",
                year: 2013,
                rate: 3.8,
                avaliations:1002,
                shortDescription: "Dezesseis histórias fantásticas, algumas escritas há mais de cem anos, outras inéditas, selecionadas por ninguém menos que o aclamado autor de Coraline e outros tantos sucessos, Neil Gaiman.",
                description: "Dezesseis histórias fantásticas, algumas escritas há mais de cem anos, outras inéditas, selecionadas por ninguém menos que o aclamado autor de Coraline e outros tantos sucessos, Neil Gaiman. Como o título sugere, Criaturas estranhas é uma coletânea de contos povoada por seres fantásticos, magníficos e às vezes assustadores. <br>Assinadas por autores clássicos de ficção científica e fantasia, como Anthony Boucher e Diana Wynne Jones, a escritores contemporâneos, como Nnedi Okorafor e o próprio Gaiman, as histórias, que parecem ter saído de um sonho, ou talvez de um pesadelo, têm em comum o olhar atento e único de Neil Gaiman para o insólito. Cada conto é precedido de um comentário do escritor, que visa a provocar ainda mais a imaginação do leitor.",
                bookCover: "https://images2.imgbox.com/1b/26/iZkMqd4L_o.png",
            },
            {
                id: 4,
                slug: "fumaca-e-espelhos",
                title: "Fumaça e espelhos",
                category: "Conto / Ficção",
                year: 1998,
                rate: 4.2,
                avaliations:1500,
                shortDescription: "Dos 31 contos (e poesias) que compõem Fumaça e espelhos, são poucos os que não surpreendem de cara pelas ideias. E os que não chamam atenção nas primeiras linhas geram várias surpresas posteriores.",
                description: "Dos 31 contos (e poesias) que compõem Fumaça e espelhos, são poucos os que não surpreendem de cara pelas ideias. E os que não chamam atenção nas primeiras linhas geram várias surpresas posteriores, pois você nunca sabe se aquele jovem pacato é um lobisomem ou se o heróico narrador do conto é um assassino. Ou mesmo o assassinado.<br>Fumaça e espelhos é uma coletânea de textos que Neil Gaiman escreveu nas décadas de 80 e 90. Na categoria de escritor ficcionista profissional, ele teve contos encomendados e publicados por diversas revistas e coletâneas, o que logo se nota pela diversidade de temas. Há desde a sua conhecida predileção por terror fantástico e magia até um conto erótico. Um elemento, porém, une todos os textos: seu vinculo com a tradição.",
                bookCover: "https://images2.imgbox.com/1c/a3/DpM5Ykks_o.png",
            },
            {
                id: 5,
                slug: "sandaman-fim-dos-mundos",
                title: "Sandman - Fim dos mundos",
                category: "Terror / Literatura fantástica",
                year: 1994,
                rate: 4.7,
                avaliations:451,
                shortDescription: "Oitavo volume das obras completas de Sandman, Fim do Mundo é um conjunto de histórias curtas interligadas.",
                description: "Oitavo volume das obras completas de Sandman, Fim do Mundo é um conjunto de histórias curtas interligadas. Depois de um acidente de carro durante uma tempestade de neve, Brant Tucker é guiado por uma voz misteriosa até uma estranha hospedaria: 'Fim do Mundo'. Ali se encontram pessoas de todas as eras, reinos e dimensões - na verdade, a estalagem serve como abrigo para pessoas perdidas durante 'tempestades de realidade'. <br>Enquanto esperam o fim do temporal, os viajantes ali reunidos contam histórias extraordinárias, desde o reino mágico de Arcádie e seus habitantes até os turbulentos EUA das décadas de 60 e 70, formando uma narrativa que remete aos Contos de Cantebury de escritor inglês Geoffrey Chaucer. Antes de Sandman, nenhuma série em quadrinhos tinha alcançado tanto sucesso de crítica e de público.",
                bookCover: "https://images2.imgbox.com/70/b5/sDDKRXgR_o.png",
            },
            {
                id: 6,
                slug: "lugar-nenhum",
                title: "Lugar nenhum",
                category: "Mito / Fantasia contemporênea",
                year: 1996,
                rate: 4.7,
                avaliations:976,
                shortDescription: "Publicado pela primeira vez em 1997, a partir do roteiro para uma série de TV, o sombrio e hipnótico Lugar Nenhum, primeiro romance de Neil Gaiman.",
                description: "Publicado pela primeira vez em 1997, a partir do roteiro para uma série de TV, o sombrio e hipnótico Lugar Nenhum, primeiro romance de Neil Gaiman, anunciou a chegada de um grande nome da literatura contemporânea e se tornou um marco da fantasia urbana. Ao longo dos anos, diferentes versões foram publicadas nos Estados Unidos e na Inglaterra, e Neil Gaiman elaborou, a partir desse material, um texto que viesse a ser definitivo: esta edição preferida do autor.<br>Em Lugar Nenhum, Richard Mayhew é um homem simples de coração bom que tem a vida transformada quando ajuda uma jovem que encontra ferida numa calçada. De um dia para o outro, Richard se torna invisível na Londres que sempre conheceu: não tem mais trabalho, não tem mais noiva, não tem mais casa. Para recuperar sua vida, ele se embrenha em um mundo que nunca sonhou existir, uma cidade que se abre nos esgotos e nos túneis subterrâneos: a chamada Londres de Baixo, em que personagens únicos e cenários mirabolantes fazem a Londres de Cima parecer uma mera paisagem cinza.",
                bookCover: "https://images2.imgbox.com/37/cf/y6bre42X_o.png",
            },
            {
                id: 7,
                slug: "livro-do-cemiterio",
                title: "Livro do cemitério",
                category: "Terror / Literatura fantástica",
                year: 2008,
                rate: 4.7,
                avaliations:721,
                shortDescription: "Enquanto seus pais e irmã são impiedosamente assassinados por um misterioso homem chamado Jack, um bebê consegue escapar de seu berço e se aventurar pelo mundo.",
                description: "Coleção Phobos Ganhador da medalha Newbery (2009), do Prêmio Hugo de Melhor Romance (2009), do Locus Award de Melhor Romance Juvenil (2009) e da Medalha Carnegie (2010). Enquanto seus pais e irmã são impiedosamente assassinados por um misterioso homem chamado Jack, um bebê consegue escapar de seu berço e se aventurar pelo mundo. <br>Uma série de coincidências, aliada a uma grande dose de sorte, salva o pequeno de ter um destino tão trágico quanto o de sua família. Com um começo sombrio e violento, diferente do seu habitual, o escritor inglês provoca arrepios no leitor. A história do bebê sortudo e fujão começa quando ele chega à rua e sobe a colina em direção ao velho cemitério.Ele é perseguido pelo assassino de seus familiares. Já dentro do cemitério o neném conhece os habitantes do local. Fantasmas de outras épocas que vivem em suas covas e mausoléus e que por circunstâncias do destino são forçados a adotar e batizar o bebê, agora chamado de Ninguém Owens, o Nin, para salvá-lo do seu perseguidor.",
                bookCover: "https://images2.imgbox.com/a3/d6/j0gKc7ja_o.png",
            },
            {
                id: 8,
                slug: "sandman-versao-definitiva-vol-1",
                title: "Sandman - Versão definitiva (Vol 1)",
                category: "Terror / Literatura fantástica",
                year: 2006,
                rate: 4.9,
                avaliations:1047,
                shortDescription: "Poucas HQs na história do mundo ocidental transcenderam o gênero e romperam barreiras como Sandman conseguiu.",
                description: "RELANÇAMENTO: “Vou revelar-te o que é o medo num punhado de pó.” Foi essa frase de T.S. Eliot que serviu para embalar o lançamento dessa série e também dar asas a imaginação de Neil Gaiman, um britânico destinado a criar uma das séries mais revolucionárias e inovadoras dos quadrinhos contemporâneos. Poucas HQs na história do mundo ocidental transcenderam o gênero e romperam barreiras como Sandman conseguiu. <br>Mesclando mitologias modernas e fantasia sombria, além de acrescentar elementos modernos, históricos e míticos, Sandman foi considerada uma das séries mais artisticamente ambiciosas dos quadrinhos. Quando foi concluída, em 1996, já tinha mudado a nona arte para sempre e se tornado um fenômeno de cultura pop, bem como um marco das HQs, tornando difusa a fronteira imaginária entre os quadrinhos de massa e o que consideramos como arte.",
                bookCover: "https://images2.imgbox.com/71/e7/vIjiN4O3_o.png",
            },
            {
                id: 9,
                slug: "coraline",
                title: "Coraline",
                category: "Terror / Ficção paranormal",
                year: 2002,
                rate: 4.9,
                avaliations:14257,
                shortDescription: "Certas portas não devem ser abertas. E Coraline descobre isso pouco tempo depois de chegar com os pais à sua nova casa, um apartamento em um casarão antigo ocupado por vizinhos excêntricos.",
                description: "Certas portas não devem ser abertas. E Coraline descobre isso pouco tempo depois de chegar com os pais à sua nova casa, um apartamento em um casarão antigo ocupado por vizinhos excêntricos e envolto por uma névoa insistente, um mundo de estranhezas e magia, o tipo de universo que apenas Neil Gaiman pode criar. <br>Ao abrir uma porta misteriosa na sala de casa, a menina se depara com um lugar macabro e fascinante. Ali, naquele outro mundo, seus outros pais são criaturas muito pálidas, com botões negros no lugar dos olhos, sempre dispostos a lhe dar atenção, fazer suas comidas preferidas e mostrar os brinquedos mais divertidos. Coraline enfim se sente... em casa. Mas essa sensação logo desaparece, quando ela descobre que o lugar guarda mistérios e perigos, e a menina se dá conta de que voltar para sua verdadeira casa vai ser muito mais difícil ― e assustador ― do que imaginava.",
                bookCover: "https://images2.imgbox.com/fc/1c/raNGfnC3_o.png",
            },
        ]
    }
}